#!/usr/bin/env bash

greet(){
	local name=$2
	echo "Hello $name (from function)"
}

for name in "$@"; do
	./hello "$name" 	# script inception
done

echo		# for printing blank line

for name in "$@"; do 
	greet "" "$name"
done


